{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "viewbinding",
    "version": "8.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-8.6.0.aar",
          "url": "viewbinding-8.6.0.aar",
          "size": 1860,
          "sha512": "e97e20712e54fc9a65ddf9f492459467d8f045a271a0b4d762aeb8b03d85666925c6fdeee67b4f4a7e0f9cc24fab0798b03867a6d5a86d82ef55b6aae0ebd538",
          "sha256": "a7edaf3d73ad364d967b837a81886ec3b40772ec61002bc8820e1c63d5d24f92",
          "sha1": "73d08f6f8362a7067649f20970aca484702f3f02",
          "md5": "2cf3ac9267a20e6a0c3459af2029ab55"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-8.6.0.aar",
          "url": "viewbinding-8.6.0.aar",
          "size": 1860,
          "sha512": "e97e20712e54fc9a65ddf9f492459467d8f045a271a0b4d762aeb8b03d85666925c6fdeee67b4f4a7e0f9cc24fab0798b03867a6d5a86d82ef55b6aae0ebd538",
          "sha256": "a7edaf3d73ad364d967b837a81886ec3b40772ec61002bc8820e1c63d5d24f92",
          "sha1": "73d08f6f8362a7067649f20970aca484702f3f02",
          "md5": "2cf3ac9267a20e6a0c3459af2029ab55"
        }
      ]
    }
  ]
}
