{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui",
    "version": "2.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.8.2-sources.jar",
          "url": "navigation-ui-2.8.2-sources.jar",
          "size": 24910,
          "sha512": "96b50ed6708a527151fa4add3794a3f4333cee63e26d9aab7f31af771abfa9256bbdd1466508bfba21400dc1656f246cfb5368f739410fd81a4f7cc196266622",
          "sha256": "c544d89db85399456165e4a3be13a614ec71c84c5d064d584a94911995eb9116",
          "sha1": "794ff876987dc95057bbf0a112930ef1023ca27f",
          "md5": "ca9cdff0e4624ed595e7fe43688ac1c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.8.2.aar",
          "url": "navigation-ui-2.8.2.aar",
          "size": 91343,
          "sha512": "b57d3bc414018d1a32846d9d598df3db556d9c8454b9544bcf7613d40f5ccda483831f71cc807a6473100ee11e30dfee94f067586c8a88f2d5864da483728220",
          "sha256": "8cd909db45f84fca44ab629a4e07e29b42e9bbcd7dce419821fe1d79d98d44f5",
          "sha1": "0a1a02c696e5b14f9b979424ef32c43599bd7cd4",
          "md5": "cfb0729ff5068d94b2e8c60eefd33b45"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.8.2.aar",
          "url": "navigation-ui-2.8.2.aar",
          "size": 91343,
          "sha512": "b57d3bc414018d1a32846d9d598df3db556d9c8454b9544bcf7613d40f5ccda483831f71cc807a6473100ee11e30dfee94f067586c8a88f2d5864da483728220",
          "sha256": "8cd909db45f84fca44ab629a4e07e29b42e9bbcd7dce419821fe1d79d98d44f5",
          "sha1": "0a1a02c696e5b14f9b979424ef32c43599bd7cd4",
          "md5": "cfb0729ff5068d94b2e8c60eefd33b45"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.8.2-versionMetadata.json",
          "url": "navigation-ui-2.8.2-versionMetadata.json",
          "size": 10087,
          "sha512": "370d68eb8362959b9b1b211d78eb714b870679b6f335b9814deec6415b691223a754a871a4c6d2350f6e67e8b76ed85afbc80bc64b6021692fe442ec6bc78c13",
          "sha256": "f0ac40e381daf5f57b29b7c39c275f7d1f7e2fb1cba88bbbed797e79284840e2",
          "sha1": "8746cd5277c85287d39d2c68e056653ae2dbcadc",
          "md5": "70874962a572d1de4719a3aa66690114"
        }
      ]
    }
  ]
}