{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment",
    "version": "2.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.8.2-sources.jar",
          "url": "navigation-fragment-2.8.2-sources.jar",
          "size": 32382,
          "sha512": "372c2df7de0a7f3368c612c05b6c24900229f690f4c6e0eb4fca8f2cd3ecf18c031315d19b6ab3d3a1e5a2f5f5249ba555b57e11761790550dab20261c40388b",
          "sha256": "b9884c64130ca3b30ee5afe3666ec29544abb2564a18db7998e611d50e786dde",
          "sha1": "c39253045a35eef580d69dad78b2328748bf53f0",
          "md5": "ecc856cd33f2b405896e519cd36520aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.slidingpanelayout",
          "module": "slidingpanelayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.8.2.aar",
          "url": "navigation-fragment-2.8.2.aar",
          "size": 97461,
          "sha512": "1f08e9a7adac02d8fa5bc46229744b6d8dfb57f49a40b005f87db879e8508e66c5b5bbafe73439406f282189c8ae5a133a46ce3aeca539026ab45037808afa26",
          "sha256": "36fcfca59033648b894e380cca111b7393384aeef3b780056e843a815ca7d8da",
          "sha1": "2094608f0e590de83199a4ec73cd37c03d4868e0",
          "md5": "703438d133dc2de3e62f5dca65a35968"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.slidingpanelayout",
          "module": "slidingpanelayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.8.2.aar",
          "url": "navigation-fragment-2.8.2.aar",
          "size": 97461,
          "sha512": "1f08e9a7adac02d8fa5bc46229744b6d8dfb57f49a40b005f87db879e8508e66c5b5bbafe73439406f282189c8ae5a133a46ce3aeca539026ab45037808afa26",
          "sha256": "36fcfca59033648b894e380cca111b7393384aeef3b780056e843a815ca7d8da",
          "sha1": "2094608f0e590de83199a4ec73cd37c03d4868e0",
          "md5": "703438d133dc2de3e62f5dca65a35968"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.8.2-versionMetadata.json",
          "url": "navigation-fragment-2.8.2-versionMetadata.json",
          "size": 12452,
          "sha512": "7c57b57599da3d685a731bdd522ca6844e616deabbcb95e51d83c17e00972ec0803570099ccf31513d16978db933f69a2b5f69db01789b5368f3815a3c11b1ab",
          "sha256": "d8625c64a346e3c45570611e43cebee4263ba42788e9774f1291b8f11b51500b",
          "sha1": "b7e090f142362c9b43cea77f9a5a6dc8dece60d2",
          "md5": "96ee8f307a5a6f1c44c66311f84fbc56"
        }
      ]
    }
  ]
}