{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-ktx",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.6.2.aar",
          "url": "fragment-ktx-1.6.2.aar",
          "size": 30127,
          "sha512": "0bf3291e258475c3f7fc6d846e0930c2d909feada8735108029558dc78f2a37f3929168d11690a505b20ec6055fce7080c624d63dd69c724a6d86eebfa08066f",
          "sha256": "460c9036b64da7ce7a066a0cb184e01451cfc44929aa1b62fe0689597f2343f8",
          "sha1": "28ad14836fdeab84c408f8bc0ce02bdeaf9c29fa",
          "md5": "d9f9c8419b830cfc7e47594b0d3387d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.6.2.aar",
          "url": "fragment-ktx-1.6.2.aar",
          "size": 30127,
          "sha512": "0bf3291e258475c3f7fc6d846e0930c2d909feada8735108029558dc78f2a37f3929168d11690a505b20ec6055fce7080c624d63dd69c724a6d86eebfa08066f",
          "sha256": "460c9036b64da7ce7a066a0cb184e01451cfc44929aa1b62fe0689597f2343f8",
          "sha1": "28ad14836fdeab84c408f8bc0ce02bdeaf9c29fa",
          "md5": "d9f9c8419b830cfc7e47594b0d3387d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.6.2-sources.jar",
          "url": "fragment-ktx-1.6.2-sources.jar",
          "size": 6463,
          "sha512": "4736cbf27b71d32cc556760c5e9978cae6bb85510d2bff2b39b351cac97c9cad6eb794768c58b76c39a5769924537ac1edbdd3014aff5b207a08004d76eaf9db",
          "sha256": "cb4898195f2dd21e06b886ec1673fdf111385850bd9c37bdd4a7ebdfddf912cf",
          "sha1": "28f33ed9b13c66f57202fc9be92d240337fce030",
          "md5": "255563c8a1375eebe8ebbf27540f4dbd"
        }
      ]
    }
  ]
}